### ISSUE TITLE
Add Brave Browser Install Instructions

### ISSUE THREAD

**Issue by Kinnardian** [BadgerWallet/badger#14]
The Chrome install instructions don't work on the Brave Browser (`v.0.57.18`). Not sure what might be the issue.

**Comment by SpendBCH** [comment]
What is your experience?

Is this working now with latest Brave (0.58.18)? The install process is the same from my experience.

Thank you! @GitCash 512 bits for @Kinnardian

**Comment by GitCash** [comment]
Hey **Kinnardian**, user **SpendBCH** tipped you **512 bits** in Bitcoin Cash ( ~ **$0.0804** ).

*[Click here to claim it!](https://gitcash.io/claim/Kinnardian)*

You can also add the "thumbs down" reaction to **SpendBCH**'s comment above to prevent future tips.

**Comment by Kinnardian** [comment]
Was using an old version of Brave. Looks to be up and running now.

**Comment by SpendBCH** [comment]
Update on this: Install in Brave from chrome web store now: https://chrome.google.com/webstore/detail/badger-wallet/jadobjbcgibiopkifknkfnohlelpocll
