### ISSUE TITLE
Download missing for Chrome

### ISSUE THREAD

**Issue by zquestz** [BadgerWallet/badger#2]
**Describe the bug**
Tells me to check the docs to get Chrome install directions. But it tells me to click "Get Started" which is only for Firefox now...

I can't seem to find the latest zip for Chrome anywhere.

**Comment by SpendBCH** [comment]
Links to both should be visible now.

Thank you!

@GitCash 1000 bits for @zquestz

**Comment by GitCash** [comment]
Hey **zquestz**, user **SpendBCH** tipped you **1000 bits** in Bitcoin Cash ( ~ **$0.445** ).

*[Click here to claim it!](https://gitcash.io/claim/zquestz)*

You can also add the "thumbs down" reaction to **SpendBCH**'s comment above to prevent future tips.
