### ISSUE TITLE
Readding Wallet Loses Token References.

### ISSUE THREAD

**Issue by zquestz** [BadgerWallet/badger#3]
**Describe the bug**
When reimporting my wallet I lost the reference to my BCHDevConSF token. It didn't come back when I imported, and I see no way to add tokens, as the search is coming soon.

**Comment by SpendBCH** [comment]
This should be resolved now in version 0.0.6

Thank you for the report! @GitCash 1000 bits for @zquestz

**Comment by GitCash** [comment]
Hey **zquestz**, user **SpendBCH** tipped you **1000 bits** in Bitcoin Cash ( ~ **$0.434** ).

*[Click here to claim it!](https://gitcash.io/claim/zquestz)*

You can also add the "thumbs down" reaction to **SpendBCH**'s comment above to prevent future tips.
