### ISSUE TITLE
Cannot find badger button docs

### ISSUE THREAD

**Issue by jcramer** [BadgerWallet/badger#8]
I cannot find docs or examples for the Badger Button.

**Comment by kosinusbch** [comment]
I second this

**Comment by Ekliptor** [comment]
apparently they are spread out here: https://www.reddit.com/r/btc/comments/9v51lu/badger_is_now_the_first_bitcoin_cash_wallet/

i would also welcome nice docs on github to integrate this into cashtippr.com

**Comment by SpendBCH** [comment]
Docs with links to demos and their source is now at https://developer.bitcoin.com/badger/docs/getting-started

Thank you! @GitCash 512 bits for @jcramer

**Comment by GitCash** [comment]
Hey **jcramer**, user **SpendBCH** tipped you **512 bits** in Bitcoin Cash ( ~ **$0.0814** ).

*[Click here to claim it!](https://gitcash.io/claim/jcramer)*

You can also add the "thumbs down" reaction to **SpendBCH**'s comment above to prevent future tips.
